require "json"

module LF
  module Data
    # Default codec for JSON-compatible Crystal types. The target type must
    # provide the readers and writers generated by `JSON::Serializable`, or an
    # equivalent `new(JSON::PullParser)` and `to_json(JSON::Builder)` contract.
    module DefaultJSONCodec
      extend self

      def load(parser : JSON::PullParser, type : T.class) : T forall T
        T.new(parser)
      end

      def dump(value : T, builder : JSON::Builder) : Nil forall T
        value.to_json(builder)
      end
    end

    # Driver-neutral JSON column encoding and decoding. Database-specific JSON
    # values are normalized before application codecs are invoked.
    module JSONColumn
      extend self

      def load(result : DB::ResultSet, codec : C.class, type : T.class) : T forall C, T
        raw = result.read
        raise JSONColumnStorageError.new(T.to_s, Nil.to_s) if raw.nil?
        load_value(raw, codec, T)
      end

      def load_nilable(
        result : DB::ResultSet,
        codec : C.class,
        type : T.class,
      ) : T? forall C, T
        raw = result.read
        return nil if raw.nil?
        load_value(raw, codec, T)
      end

      private def load_value(raw, codec : C.class, type : T.class) : T forall C, T
        parser = case raw
                 when JSON::PullParser
                   raw
                 when JSON::Any
                   JSON::PullParser.new(raw.to_json)
                 when String
                   JSON::PullParser.new(raw)
                 when Bytes
                   JSON::PullParser.new(String.new(raw))
                 else
                   raise JSONColumnStorageError.new(T.to_s, raw.class.to_s)
                 end
        value = codec.load(parser, T).as(T)
        unless parser.kind.eof?
          raise JSON::Error.new("JSON column codec did not consume the complete value")
        end
        value
      rescue error : JSONColumnError
        raise error
      rescue error
        raise JSONColumnDecodeError.new(T.to_s, error)
      end

      def dump(value : T, codec : C.class) : String forall C, T
        String.build do |io|
          JSON.build(io) do |builder|
            codec.dump(value, builder)
          end
        end
      rescue error : JSONColumnError
        raise error
      rescue error
        raise JSONColumnEncodeError.new(T.to_s, error)
      end

      def dump_query(value : T) : String forall T
        value.to_json
      rescue error : JSONColumnError
        raise error
      rescue error
        raise JSONColumnEncodeError.new(T.to_s, error)
      end
    end
  end
end
