require "../../spec_helper"
require "../../../../src/opal/data/dialects/postgresql"

describe LF::Data::Dialects::PostgreSQL::SchemaCompiler do
  dialect = LF::Data::Dialects::PostgreSQL.new
  compiler = LF::Data::Dialects::PostgreSQL::SchemaCompiler.new(dialect)

  it "renders portable PostgreSQL types, defaults, constraints, and indexes" do
    table = LF::Data::Schema::TableBuilder.new("projects")
    timestamp = Time.utc(2026, 8, 30, 12, 30, 0)
    table.generated_id("id")
    table.string("code", null: false, default: "can't")
    table.text("notes")
    table.bool("active", null: false, default: true)
    table.int32("priority", default: 2_i32)
    table.int64("version", null: false, default: 0_i64)
    table.float64("score", default: 1.5_f64)
    table.timestamp("created_at", default: timestamp)
    table.bytes("payload", default: Bytes[0x0a, 0xff])
    table.unique("code", name: "uq_projects_code")
    table.index("idx_projects_active", "active")

    statements = compiler.compile(LF::Data::Schema::CreateTable.new(table.build))

    statements.map(&.sql).should eq([
      [
        "CREATE TABLE \"projects\" (",
        "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ",
        "\"code\" VARCHAR(255) NOT NULL DEFAULT 'can''t', ",
        "\"notes\" TEXT, \"active\" BOOLEAN NOT NULL DEFAULT TRUE, ",
        "\"priority\" INTEGER DEFAULT 2, \"version\" BIGINT NOT NULL DEFAULT 0, ",
        "\"score\" DOUBLE PRECISION DEFAULT 1.5, ",
        "\"created_at\" TIMESTAMPTZ DEFAULT '2026-08-30T12:30:00Z', ",
        "\"payload\" BYTEA DEFAULT decode('0aff', 'hex'), ",
        "CONSTRAINT \"uq_projects_code\" UNIQUE (\"code\"))",
      ].join,
      %(CREATE INDEX "idx_projects_active" ON "projects" ("active")),
    ])
  end

  it "renders composite keys, foreign keys, alterations, and raw SQL" do
    table = LF::Data::Schema::TableBuilder.new("tasks")
    table.int64("tenant_id", null: false)
    table.int64("id", null: false)
    table.primary_key("tenant_id", "id", name: "pk_tasks")
    table.foreign_key(
      "tenant_id",
      references_table: "tenants",
      references_column: "id",
      name: "fk_tasks_tenant"
    )

    compiler.compile(LF::Data::Schema::CreateTable.new(table.build)).first.sql
      .should eq([
        "CREATE TABLE \"tasks\" (",
        "\"tenant_id\" BIGINT NOT NULL, \"id\" BIGINT NOT NULL, ",
        "CONSTRAINT \"pk_tasks\" PRIMARY KEY (\"tenant_id\", \"id\"), ",
        "CONSTRAINT \"fk_tasks_tenant\" FOREIGN KEY (\"tenant_id\") ",
        "REFERENCES \"tenants\" (\"id\"))",
      ].join)

    column = LF::Data::Schema::ColumnDefinition.new(
      "done",
      LF::Data::Schema::ColumnType::Bool,
      false,
      LF::Data::Schema::DefaultValue.new(false),
      false
    )
    operations = [
      LF::Data::Schema::AddColumn.new("tasks", column),
      LF::Data::Schema::RenameColumn.new("tasks", "done", "completed"),
      LF::Data::Schema::DropIndex.new("idx_tasks_done"),
      LF::Data::Schema::DropTable.new("tasks"),
      LF::Data::Schema::RenameTable.new("tasks", "renamed_tasks"),
      LF::Data::Schema::RawSQL.new("backfill", "UPDATE tasks SET done = FALSE"),
    ] of LF::Data::Schema::Operation

    operations.flat_map { |operation| compiler.compile(operation) }.map(&.sql)
      .should eq([
        %(ALTER TABLE "tasks" ADD COLUMN "done" BOOLEAN NOT NULL DEFAULT FALSE),
        %(ALTER TABLE "tasks" RENAME COLUMN "done" TO "completed"),
        %(DROP INDEX "idx_tasks_done"),
        %(DROP TABLE "tasks"),
        %(ALTER TABLE "tasks" RENAME TO "renamed_tasks"),
        "UPDATE tasks SET done = FALSE",
      ])
  end
end
